version: '3.9'

services:
  normalize-it:
    volumes:
      - .:/code
    container_name: normalize-it-hackathon
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "Rscript app.r && tail -f app.r"
