version: '3.9'

services:
  normalize-it:
    volumes:
      - .:/code
    container_name: normalize-it-hackathon
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "Rscript scripts/batch_correct.R -o /service/data/output -f /service/data/input/ -i file_metadata.csv"
