version: '3.9'

services:
  normalize-it:
    volumes:
      - .:/code
    container_name: normalize-it-runner
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "Rscript /code/scripts/batch_correct.R"
